SELECT * FROM BOARD WHERE BTYPE=1;
SELECT * FROM ATTACHMENT;
SELECT * FROM CATEGORY;
SELECT * from MEMBER;
SELECT * from NOTICE;
SELECT * FROM REPLY;

INSERT INTO BOARD VALUES(SEQ_BID.NEXTVAL, 1, ?, ?, ?, ?, 0, SYSDATE, SYSDATE, 'Y')

SELECT * FROM(
SELECT ROWNUM RNUM, A.* FROM (
SELECT BID, BTYPE, C.CNAME, BTITLE,BCONTENT, M.USER_NAME, BCOUNT, CREATE_DATE, 
B.MODIFY_DATE, B.STATUS FROM BOARD B 
JOIN CATEGORY C USING (CID) 
JOIN MEMBER M ON(BWRITER=USER_NO) 
WHERE BTYPE=1 AND B.STATUS='Y'
ORDER BY BID DESC) A )
WHERE RNUM BETWEEN ? AND ?;

CREATE OR REPLACE VIEW BDETAIL
AS
SELECT B.BID, 
B.BTYPE,
C.CNAME, 
B.BTITLE, 
B.BCONTENT,
B.BWRITER, USER_NAME,
B.BCOUNT, B.CREATE_DATE, B.MODIFY_DATE,B.STATUS FROM BOARD B JOIN CATEGORY C USING(CID) JOIN MEMBER M ON(B.BWRITER=M.USER_NO);

SELECT * FROM BDETAIL;


